# Generated by Django 4.0.5 on 2022-07-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='News',
        ),
    ]
