# Generated by Django 4.0.5 on 2022-07-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='service_des',
        ),
    ]
